import type { Metadata } from "next";
import "./globals.css";
import {   Faster_One, Lemon, Rubik_Doodle_Shadow, Rubik_Moonrocks} from "next/font/google"
import Providers from "./components/Providers";

const handWritten_Cursive=Rubik_Doodle_Shadow({
  subsets: ["latin"],
  weight: "400",
});



export const metadata: Metadata = {
  title: "Sips",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${handWritten_Cursive.className} font-bold antialiased`}>
       <Providers>{children}</Providers>
  
      </body>
    </html>
  );
}
